### ISSUE TITLE
Validator.isValidIPv4String throws Error: Invalid integer: NaN if invalid string passed

### ISSUE THREAD

**Issue by saiyeek** [ip-num/ip-num#4]
`
Validator.isValidIPv4String('10.10.10.x') 
`
throws 

> Message:
    Error: Invalid integer: NaN
  Stack:
    Error: Invalid integer: NaN
        at parseStringValue (ip-num/node_modules/big-integer/BigInteger.js:1172:33)
        at parseNumberValue (ip-num/node_modules/big-integer/BigInteger.js:1189:16)

**Comment by saiyeek** [comment]
Pull request: https://github.com/ip-num/ip-num/pull/5

**Comment by dadepo** [comment]
Pull request merged!
